# Use an official Nginx image
FROM nginx:alpine

# Copy the HTML and CSS files into the container.
COPY index.html /usr/share/nginx/html/
COPY styles.css /usr/share/nginx/html/

# Expose port 80
EXPOSE 80
