name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push micro-frontend-1
        run: |
          docker build -t madhanprasath/micro-frontend-1 ./micro-frontend-1
          docker push madhanprasath/micro-frontend-1:latest

      - name: Build and push micro-frontend-2
        run: |
          docker build -t madhanprasath/micro-frontend-2 ./micro-frontend-2
          docker push madhanprasath/micro-frontend-2:latest

      - name: Build and push nginx reverse proxy
        run: |
          docker build -t madhanprasath/nginx-reverse-proxy ./nginx
          docker push madhanprasath/nginx-reverse-proxy:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull madhanprasath/micro-frontend-1:latest
            docker pull madhanprasath/micro-frontend-2:latest
            docker pull madhanprasath/nginx-reverse-proxy:latest
        
            docker stop micro-frontend-1 || true
            docker stop micro-frontend-2 || true
            docker stop nginx-reverse-proxy || true
        
            docker rm micro-frontend-1 || true
            docker rm micro-frontend-2 || true
            docker rm nginx-reverse-proxy || true
        
            docker run -d --name micro-frontend-1 madhanprasath/micro-frontend-1:latest
            docker run -d --name micro-frontend-2 madhanprasath/micro-frontend-2:latest
            docker run -d -p 80:80 --name nginx-reverse-proxy madhanprasath/nginx-reverse-proxy:latest
